### ISSUE TITLE
Adding extra headers to requests forwarding with httpForward

### ISSUE THREAD

**Issue by Mishurin** [jamesdbloom/mockserver-node#2]
Is there any simple way to add additional headers to each intercepted requests before forwarding?

**Comment by Mishurin** [comment]
From the documentation of the mockserver-client I noticed that only mockSimpleResponse may have default headers which is not enough for me since I want to add default headers for each forwarded request using './*' pattern.

**Comment by jamesdbloom** [comment]
Sorry for the slow response, most issues are added to the [mockserver  repo](https://github.com/jamesdbloom/mockserver) so this was missing.  I think what you need is now available via http://mock-server.com/mock_server/creating_expectations.html#button_forward_overridden.  If this doesn't meet your need please open a new issue in the main repo unless the issue is related specifically to the node code.
